# Generated by Django 3.1.3 on 2020-11-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_facedetection_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facedetection',
            name='strength',
        ),
    ]
