# Generated by Django 3.1.3 on 2020-11-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_remove_facedetection_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
