# Generated by Django 3.1.3 on 2020-11-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0014_auto_20201118_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jupyter_file', models.FileField(upload_to='notebooks')),
                ('pickled_file', models.FileField(upload_to='binary_objects')),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
    ]
