# Generated by Django 3.1.3 on 2020-11-22 18:48

import Models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0019_usermodel_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceProtection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='submitted_pictures', validators=[Models.validators.validate_pic_type, Models.validators.validate_size])),
            ],
        ),
    ]
