# Generated by Django 3.1.3 on 2020-11-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0020_faceprotection'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceprotection',
            name='strength',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
