# Generated by Django 3.1.3 on 2020-11-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
        ('NewsSection', '0002_auto_20201108_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Profiles.profile'),
            preserve_default=False,
        ),
    ]
