# Generated by Django 3.1.3 on 2020-11-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSection', '0003_news_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='author_id',
            new_name='author',
        ),
    ]
