# Generated by Django 3.1.3 on 2020-11-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSection', '0007_comment_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
