# Generated by Django 3.1.3 on 2020-11-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSection', '0008_auto_20201116_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
    ]
