# Generated by Django 3.1.3 on 2020-11-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSection', '0011_auto_20201116_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text2',
            field=models.CharField(max_length=500),
        ),
    ]
