# Generated by Django 3.1.3 on 2020-11-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSection', '0012_auto_20201116_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text2',
            new_name='comment',
        ),
    ]
