# Generated by Django 3.1.3 on 2020-11-18 19:06

import NewsSection.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSection', '0014_auto_20201116_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=500, validators=[NewsSection.validators.only_english_validator]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50, validators=[NewsSection.validators.only_english_validator]),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=3000, validators=[NewsSection.validators.only_english_validator]),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50, validators=[NewsSection.validators.only_english_validator]),
        ),
    ]
